// <auto-generated />
using System;
using LinFx.Extensions.EntityFrameworkCore;
using LinFx.Extensions.TenantManagement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IdentityService.Migrations.TenantManagementDb
{
    [DbContext(typeof(TenantManagementDbContext))]
    partial class TenantManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_DatabaseProvider", EfDatabaseProvider.Sqlite)
                .HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("LinFx.Extensions.TenantManagement.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreationTime");

                    b.Property<string>("CreatorId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatorId");

                    b.Property<string>("DeleterId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("DeleterId");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ExtraProperties");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastModificationTime");

                    b.Property<string>("LastModifierId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Tenants", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
